Repository sync-without-async/Rehab-BackEnd, pull requests merged in 2023-11, with the labels that each got.

#22 [BE/refactor] 예약 생성시 관련된 방, 오디오 생성
  .gitignore
  src/main/java/com/hallym/rehab/domain/reservation/dto/ReservationRequestDTO.java
  src/main/java/com/hallym/rehab/domain/reservation/dto/ReservationResponseByAdminDTO.java
  src/main/java/com/hallym/rehab/domain/reservation/dto/ReservationResponseByUserDTO.java
  src/main/java/com/hallym/rehab/domain/reservation/entity/Reservation.java
  src/main/java/com/hallym/rehab/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hallym/rehab/domain/room/controller/RoomController.java
  src/main/java/com/hallym/rehab/domain/room/dto/AudioRequestDTO.java
  src/main/java/com/hallym/rehab/domain/room/entity/Audio.java
  src/main/java/com/hallym/rehab/domain/room/entity/Room.java
  src/main/java/com/hallym/rehab/domain/room/service/AudioServiceImpl.java
  src/main/java/com/hallym/rehab/global/config/SslConfig.java
Labels: 🔧 fix_issue

#28 [BE/ feat] 환자 차트를 생성하여 진료 기록을 관리하고, 나의 환자 목록을 볼 수 있다.
  src/main/java/com/hallym/rehab/domain/chart/controller/ChartController.java
  src/main/java/com/hallym/rehab/domain/chart/controller/RecordController.java
  src/main/java/com/hallym/rehab/domain/chart/dto/ChartRequestDTO.java
  src/main/java/com/hallym/rehab/domain/chart/dto/ChartResponseDTO.java
  src/main/java/com/hallym/rehab/domain/chart/dto/OnlineRecordDTO.java
  src/main/java/com/hallym/rehab/domain/chart/dto/RecordDTO.java
  src/main/java/com/hallym/rehab/domain/chart/entity/Chart.java
  src/main/java/com/hallym/rehab/domain/chart/entity/Record.java
  src/main/java/com/hallym/rehab/domain/chart/repository/ChartRepository.java
  src/main/java/com/hallym/rehab/domain/chart/repository/RecordRepository.java
  src/main/java/com/hallym/rehab/domain/chart/repository/search/ChartSearch.java
  src/main/java/com/hallym/rehab/domain/chart/repository/search/ChartSearchImpl.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartService.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartServiceImpl.java
  src/main/java/com/hallym/rehab/domain/chart/service/RecordService.java
  src/main/java/com/hallym/rehab/domain/chart/service/RecordServiceImpl.java
  src/main/java/com/hallym/rehab/domain/reservation/controller/ReservationController.java
  src/main/java/com/hallym/rehab/domain/reservation/dto/ReservationResponseByPatientDTO.java
  src/main/java/com/hallym/rehab/domain/reservation/dto/ReservationResponseByStaffDTO.java
  src/main/java/com/hallym/rehab/domain/reservation/entity/Reservation.java
  src/main/java/com/hallym/rehab/domain/reservation/service/ReservationService.java
  src/main/java/com/hallym/rehab/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/controller/UserController.java
  src/main/java/com/hallym/rehab/domain/user/dto/TherapistDTO.java
  src/main/java/com/hallym/rehab/domain/user/entity/Staff.java
  src/main/java/com/hallym/rehab/domain/user/repository/StaffRepository.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserService.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserServiceImpl.java
  src/test/java/com/hallym/rehab/CreateStaffAndUserTest.java
  src/test/java/com/hallym/rehab/domain/chart/ChartRepositoryTest.java
Labels: 🔑 auth, 🔨 feature, 🔧 fix_issue, 📈 test

#29 [BE / feat] 환자 로그인을 구현하고, 차트 생성 시, 환자 계정 아이디를 반환한다
  src/main/java/com/hallym/rehab/domain/chart/controller/ChartController.java
  src/main/java/com/hallym/rehab/domain/chart/controller/RecordController.java
  src/main/java/com/hallym/rehab/domain/chart/entity/Chart.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartService.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartServiceImpl.java
  src/main/java/com/hallym/rehab/domain/chart/service/RecordService.java
  src/main/java/com/hallym/rehab/domain/chart/service/RecordServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/entity/MemberRole.java
  src/main/java/com/hallym/rehab/domain/user/entity/Patient.java
  src/main/java/com/hallym/rehab/domain/user/entity/Staff.java
  src/main/java/com/hallym/rehab/domain/user/repository/StaffRepository.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserServiceImpl.java
  src/main/java/com/hallym/rehab/global/security/APIUserDetailsService.java
  src/test/java/com/hallym/rehab/CreateStaffAndUserTest.java
  src/test/java/com/hallym/rehab/domain/chart/ChartRepositoryTest.java
  src/test/java/com/hallym/rehab/domain/member/PatientRepositoryTests.java
  src/test/java/com/hallym/rehab/domain/program/repository/ProgramRepositoryTestWithDetail.java
  src/test/java/com/hallym/rehab/domain/program/service/ProgramServiceImplTest.java
  src/test/java/com/hallym/rehab/domain/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/hallym/rehab/domain/reservation/repository/TimeRepositoryTest.java
  src/test/java/com/hallym/rehab/domain/reservation/service/ReservationServiceImplTest.java
  src/test/java/com/hallym/rehab/domain/room/repository/RoomRepositoryTest.java
  src/test/java/com/hallym/rehab/domain/room/service/AudioServiceImplTest.java
  src/test/java/com/hallym/rehab/domain/room/service/RoomServiceTest.java
  src/test/java/com/hallym/rehab/domain/video/repository/VideoRepositoryTest.java
  src/test/java/com/hallym/rehab/domain/video/service/VideoServiceTest.java
Labels: 🔑 auth, 🔨 feature, 🔧 fix_issue

#30 [BE / feat] 환자는 내 정보를 조회하며 Docker Image 생성 시, 태그를 생성한다.
  .github/workflows/deploy.yml
  src/main/java/com/hallym/rehab/domain/chart/service/ChartServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/controller/UserController.java
  src/main/java/com/hallym/rehab/domain/user/dto/PatientDTO.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserService.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserServiceImpl.java
Labels: 🔨 feature, 🔧 fix_issue, ⚙️ infra, 🏢 release

#34 [BE, refactor] 환자 차트 상세 조회 메소드를 분리하고, 반환할 필드들을 선언한다.
  src/main/java/com/hallym/rehab/domain/chart/controller/ChartController.java
  src/main/java/com/hallym/rehab/domain/chart/dto/ChartResponseDTO.java
  src/main/java/com/hallym/rehab/domain/chart/repository/ChartRepository.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartService.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartServiceImpl.java
  src/main/java/com/hallym/rehab/domain/program/dto/ProgramRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/reservation/dto/ReservationResponseByPatientDTO.java
  src/main/java/com/hallym/rehab/domain/reservation/entity/Reservation.java
  src/main/java/com/hallym/rehab/domain/room/dto/AudioRequestDTO.java
  src/main/java/com/hallym/rehab/domain/room/entity/Audio.java
  src/main/java/com/hallym/rehab/domain/room/service/AudioServiceImpl.java
Labels: 🔨 feature, 🔧 fix_issue, 🔥 hotfix

#35 [BE / Feat] 환자의 비대면 진료기록 목록을 조회한다.
  .github/workflows/deploy.yml
  src/main/java/com/hallym/rehab/domain/chart/controller/ChartController.java
  src/main/java/com/hallym/rehab/domain/chart/dto/AIRecordDTO.java
  src/main/java/com/hallym/rehab/domain/chart/dto/ChartResponseDTO.java
  src/main/java/com/hallym/rehab/domain/chart/dto/OnlineRecordDTO.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartService.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartServiceImpl.java
  src/main/java/com/hallym/rehab/domain/reservation/repository/ReservationRepository.java
  src/test/java/com/hallym/rehab/domain/room/service/AudioServiceImplTest.java
Labels: 🔨 feature, ⚙️ infra, 🏢 release

#38 [BE / infra] 민감정보 파일을 복호화하여 사용한다
  .github/workflows/deploy.yml
  src/main/java/com/hallym/rehab/domain/email/controller/EmailController.java
  src/main/java/com/hallym/rehab/domain/email/service/EmailService.java
  src/main/java/com/hallym/rehab/domain/email/service/EmailServiceImpl.java
  src/main/java/com/hallym/rehab/global/config/EmailConfig.java
  src/main/resources/application.tar.gpg
  src/main/resources/application.yml
Labels: ⚙️ infra, 🏢 release

#39 [BE / refactor] audio 업로드 체크방식 리팩토링
  ObjectStorageGuide_EN.md
  ObjectStorageGuide_KO.md
  src/main/java/com/hallym/rehab/domain/reservation/controller/ReservationController.java
  src/main/java/com/hallym/rehab/domain/reservation/entity/Reservation.java
  src/main/java/com/hallym/rehab/domain/room/dto/UploadAudioDTO.java
  src/main/java/com/hallym/rehab/domain/room/service/AudioService.java
  src/main/java/com/hallym/rehab/domain/room/service/AudioServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/controller/UploadController.java
  src/main/java/com/hallym/rehab/domain/video/dto/VideoRequestDTO.java
  src/main/java/com/hallym/rehab/domain/video/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/video/service/VideoServiceImpl.java
  src/main/java/com/hallym/rehab/global/s3/S3Client.java
  src/main/java/com/hallym/rehab/global/s3/S3Util.java
  src/main/java/com/hallym/rehab/global/s3/dto/UploadResponseDTO.java
  src/main/java/com/hallym/rehab/global/s3/dto/UploadVideoResponseDTO.java
  src/test/java/com/hallym/rehab/domain/program/service/ProgramServiceImplTest.java
  src/test/java/com/hallym/rehab/domain/room/service/AudioServiceImplTest.java
  src/test/java/com/hallym/rehab/domain/video/service/VideoServiceTest.java
  src/test/java/com/hallym/rehab/global/config/S3ClientTest.java
Labels: 🔥 hotfix, 📈 test

#44 [BE / fix ] 차트 목록에서 조회하는 Merics_rate를 삭제한다.
  .github/workflows/deploy.yml
  Dockerfile
  src/main/java/com/hallym/rehab/domain/chart/MetricsUtil.java
  src/main/java/com/hallym/rehab/domain/chart/dto/ChartListAllDTO.java
  src/main/java/com/hallym/rehab/domain/chart/entity/Chart.java
  src/main/java/com/hallym/rehab/domain/chart/repository/search/ChartSearchImpl.java
  src/main/java/com/hallym/rehab/domain/chart/service/ChartServiceImpl.java
  src/main/java/com/hallym/rehab/global/config/SslConfig.java
  src/main/resources/static/client.js
  src/main/resources/static/client2.js
  src/main/resources/static/index.html
Labels: 🔧 fix_issue, 🔥 hotfix
